server:
  port: 9095
spring:
  mvc.throw-exception-if-no-handler-found: true
  application:
    name: sol-app
  data:
    mongodb:
      auto-index-creation: true
      database: sol
      username: admin
      password: admin
      port: 27017
      host: 127.0.0.1


rcore:
  security:
    jwt:
      key: OcgPpNVoa-yLNxmelnc6ErULJ-O_2m7ezTQqXlca1jU=

foodtechlab:
  security:
    password: root
    username: microservice
    jwt:
      secret: secret01234567890ABCDEFGHIJKLMNO
    secretWord: secretWord
    auth:
      email: microservice
      password: root
      username: microservice
  infrastructure:
    microservice:
      auth-service:
        url: https://service.sol-auth.maslov.tech/
#        url: http://localhost:9102/
      logging-service:
        enable-logging-for-paths: /api/v1/
infrastructure:
  microservice:
    auth-service: https://service.sol-auth.maslov.tech/
#    auth-service: http://localhost:9102/

feign.hystrix.enabled: true

java.mail:
  username: data-manager@maslov.tech
  password: PKrU25g*CW2S