server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: sol-app-backend-stage
  data:
    mongodb:
      auto-index-creation: true
      database: sol-app-backend-stage
      port: 27017
      host: database


rcore:
  security:
    jwt:
      key: OcgPpNVoa-yLNxmelnc6ErULJ-O_2m7ezTQqXlca1jU=

foodtechlab:
  build:
    version: 1
  security:
    password: root
    username: microservice
    jwt:
      secret: secret01234567890ABCDEFGHIJKLMNO
    secretWord: secretWord
    auth:
      email: microservice
      password: root
      username: microservice
  infrastructure:
    microservice:
      auth-service:
        #        url: https://service.sol-auth.maslov.tech/
        url: http://ftl-auth-service:8080
      logging-service:
        enable-logging-for-paths: /api/v1/

feign.hystrix.enabled: true

java.mail:
  username: data-manager@maslov.tech
  password: PKrU25g*CW2S

#Конфигурация документации Swagger
springdoc:
  packagesToScan: com.sol
  pathsToMatch: /api/**, /not-secure/**

#Принудительно отключаем старую версию работы с конфигурацией, что бы избежать конфликтов
springfox:
  documentation:
    enabled: false